# Generated by Django 3.0.6 on 2020-06-03 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200601_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='current_clr_matching_amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=50),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_email',
            field=models.EmailField(default='owner@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default='KJHGFTY765456UJHGFFGH', max_length=255),
            preserve_default=False,
        ),
    ]
