# Generated by Django 3.0.6 on 2020-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_uuid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
