# Generated by Django 3.0.6 on 2020-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200608_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='images',
            new_name='staff_images',
        ),
        migrations.AddField(
            model_name='business',
            name='business_video_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.TextField(default='test.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='facebook_profile_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_profile_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='main_business_image',
            field=models.TextField(default='test.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='website_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.TextField(),
        ),
    ]
