# Generated by Django 3.0.6 on 2020-06-10 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200609_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='expenditure_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='staff_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None),
        ),
    ]
