# Generated by Django 3.0.6 on 2020-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200610_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='matched_amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=50),
        ),
    ]
