# Generated by Django 3.0.6 on 2020-06-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_donation_matched_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='saturation',
            new_name='cap_reached',
        ),
    ]
