# Generated by Django 3.0.6 on 2020-06-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200618_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLRRound',
            fields=[
                ('round_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('round_status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=256, null=True)),
            ],
        ),
    ]
