# Generated by Django 3.0.6 on 2020-06-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clrround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='round_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CLRRound'),
        ),
    ]
