# Generated by Django 3.0.6 on 2020-06-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200619_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='round_number',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.CLRRound'),
        ),
    ]
