# Generated by Django 3.0.6 on 2020-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200625_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accepting_donations',
            field=models.BooleanField(default=True, help_text='Whether or not this contribution is being accepted', verbose_name='Accepting Donations ?'),
        ),
    ]
